# Generated by Django 4.1.7 on 2023-03-02 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('surName', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('registerData', models.DateTimeField(auto_now_add=True)),
                ('catPerson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category')),
            ],
        ),
    ]
